# Generated by Django 4.2.7 on 2023-11-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0004_blog_bookmark_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
