# Generated by Django 4.2.3 on 2023-11-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0004_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
